### ISSUE TITLE
Building a Market Maker bot tutorial

### ISSUE THREAD

**Issue by amejiarosario** [coinbase/coinbase-pro-trading-toolkit#108]
Since, it said comming soon in October, I have been waiting for this tutorial for months...

https://coinbase.github.io/gdax-tt/gtt_advanced_marketmaking.html

Any plans to complete this tutorial or at least guidelines/pointers how can be achieved @CjS77?

**Comment by JamesMcMurran** [comment]
you can use mine found at 
https://github.com/JamesMcMurran/GDaxMarketMakerTrader/

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
