### ISSUE TITLE
error running yarn test

### ISSUE THREAD

**Issue by hzmbeyond80** [coinbase/coinbase-pro-trading-toolkit#123]
I ran yarntest.txt and got the following error. please advice 
[yarntest.txt](https://github.com/coinbase/gdax-tt/files/1585478/yarntest.txt)

**Comment by wahnker** [comment]
I have this problem too.  I'm a newb...

**Comment by nbet1** [comment]
Just starting out but also getting this error

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
