### ISSUE TITLE
MaxListenersExceededWarning in bittrex

### ISSUE THREAD

**Issue by objuan** [coinbase/coinbase-pro-trading-toolkit#127]
Hi,
Congratulations for your library I found it very useful.

I would like to add 12 new LiveOrderbook object with different products to the bittrex feed but i receive the follow WARNING: 

(node:3764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit

Is this only a warning or something else? 

thank you

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
