### ISSUE TITLE
Gemini Integration

### ISSUE THREAD

**Issue by patwhite** [coinbase/coinbase-pro-trading-toolkit#13]
Gemini has an API that should be easy to implement, with websocket streaming updates and a private api.

https://docs.gemini.com/websocket-api/

**Comment by github-ajt** [comment]
#35 has the market data feed with a live demo of the Gemini orderbook. With @CjS77 addition to use CCXT, most Gemini API calls are available. The private API will be included in another PR.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
