### ISSUE TITLE
Paper Trading capability

### ISSUE THREAD

**Issue by jleonelion** [coinbase/coinbase-pro-trading-toolkit#135]
Paper trading is a great way to test out algorithms/bots without risking real money.  I've implemented a "Paper Exchange" and would be happy to share it with the community.

This capability also creates a stepping stone to support back-testing at a future point.

**Comment by sfkiwi** [comment]
Do you still plan on sharing this with the community?

**Comment by DannyHinshaw** [comment]
@jleonelion it looks like you've made some pretty good progress with this. This is something I will be needing in the near future, and rather than create my own I could help if you like.

**Comment by jleonelion** [comment]
@DannyHinshaw, by all means, feel free to jump in.  I have some compiler errors after the last merge from the main line and I just haven't had time to get those complete.  If you have any questions about the design or approach, please let me know.  There are many different unit tests exercising the behavior (and I tried to comment the code)

**Comment by DannyHinshaw** [comment]
@jleonelion I was able to get started today and got the most recent gdax-tt master branch merged in and fixed the compiler/tslint errors, and all tests are working (except two for paper that just go `pending`). If you could give me permissions to your fork I can go ahead and push this branch up and we can use it for a starting point to continue the conversation and get this feature finished.

**Comment by jleonelion** [comment]
@DannyHinshaw Excellent to hear of your progress.  I have added you as a collaborator to my fork of gdax-tt.  The two "pending" tests aren't mandatory, but they were scenarios that came to mind while I was in the midst of building things out.  If @CjS77 will no accept changes when there are pending tests, then I'd suggest commenting them out (or looking at them and implementing).

**Comment by DannyHinshaw** [comment]
@jleonelion trying to get in touch with you on that closed pull request on your fork. Not sure if you've seen yet or not, hoping we can knock this out soon.

**Comment by jleonelion** [comment]
Danny,

Feel free to push these changes to the main line. I will be busy with daughter’s graduation for the rest of the week.

**Comment by DannyHinshaw** [comment]
@jleonelion for whatever reason I was never alerted for your response here, looks like you already took care of submitting the PR though which is great :+1: 

I looked at the PR and saw some comments in review on a few small changes requested by @blair dating back to March. Somehow I missed those when I was fixing the paper branch initially, if you like I can take care of them if you haven't started already. Just let me know.

(Congrats on the daughter's grad btw!)

**Comment by jleonelion** [comment]
Danny

Please feel free to do it. I also overlooked.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
