### ISSUE TITLE
Errors with src/exchanges/ccxt/index.d.ts

### ISSUE THREAD

**Issue by bigbluerope** [coinbase/coinbase-pro-trading-toolkit#141]
I started a new project in VSCode and ran "yarn add gdax-trading-toolkit".  I get these two errors.
> Executing task: tsc -p "c:\Users\schul\source\repos\ProductionCode\CryptoTrading\CryptoTrader5\tsconfig.json" <

node_modules/gdax-trading-toolkit/build/src/exchanges/ccxt/index.d.ts(15,10): error TS2305: Module ''ccxt'' has no exported member 'CCXTMarket'.
node_modules/gdax-trading-toolkit/build/src/exchanges/ccxt/index.d.ts(15,22): error TS2305: Module ''ccxt'' has no exported member 'CCXTOHLCV'.

my tsconfig.json is
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "lib": ["es6", "es2016", "es2016.array.include", "dom", "es2017.object"],
    //"noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "strictNullChecks": false,
    "experimentalDecorators": true,
    "outDir": "build",
    "sourceMap": true
    //"allowJs": true // I commented this out because each time I built, it put a new /build directory under my existing .build directory, so i ended up with recursive build directories
  },
  "exclude": [
    "node_modules"
  ]
}

I tried starting over several times but I always end up with the same two errors. I am able to connect via REST and websocket calls if I ignore the errors and just run, but obviously something is wrong.  I would very much appreciate any help you can give to me.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/ccxt.d.ts

**Comment by bigbluerope** [comment]
Thanks for the feedback kroitor, but I don't understand what you're trying to tell me.  I can see that ccxt.d.ts does not have a CCXTMarket exported member, so I understand what the error is saying.  But .../exchanges/ccxt/index.d.ts uses CCXTMarket and is attempting to import it from ccxt, so I still don't know how to resolve the issue.

**Comment by kroitor** [comment]
Sorry, I wasn't clear enough, the link was mostly for the GDAX TT team members to check for updated class definitions there.

**Comment by toledoal** [comment]
It appears that CCXTMarket and CCXTOHLCV changed to just Market & OHLCV https://github.com/ccxt/ccxt/blob/master/ccxt.d.ts  
After editing gdax-trading-toolkit/build/src/exchanges/ccxt/index.d.ts to reflect the changes, the bug appears to be gone and I was able to run the tsc

**Comment by mbana** [comment]
How is the build passing? Shouldn't this have been caught as compile error?
I am running into the same issue.
Can the fix not be made upstream in this repo instead of having everyone make the change on their own version?

**Comment by Darkbladecr** [comment]
It has been four months, why have these changes not been pushed to npm ?

**Comment by mabounassif** [comment]
I'm running into a similar issue:
```
ts-node v6.1.1
node v10.5.0
typescript v2.9.2
```

the error:

```
node_modules/gdax-trading-toolkit/build/src/exchanges/ccxt/index.d.ts:15:10 - error TS2305: Module ''ccxt'' has no exported member 'CCXTMarket'.

15 import { CCXTMarket, CCXTOHLCV } from 'ccxt';
            ~~~~~~~~~~


node_modules/gdax-trading-toolkit/build/src/exchanges/ccxt/index.d.ts:15:22 - error TS2305: Module ''ccxt'' has no exported member 'CCXTOHLCV'.

15 import { CCXTMarket, CCXTOHLCV } from 'ccxt';
                        ~~~~~~~~~


```

**Comment by mabounassif** [comment]
Confirming that the break happens after version `0.1.29`

**Comment by mabounassif** [comment]
@mbana this is not failing because we are caching the `node_modules` on circleci

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
