### ISSUE TITLE
Error: A GDAX API request failed - better message

### ISSUE THREAD

**Issue by mbana** [coinbase/coinbase-pro-trading-toolkit#142]
Hi All,

In the code, we have:

https://github.com/coinbase/gdax-tt/blob/master/src/exchanges/gdax/GDAXExchangeAPI.ts#L354

```typescript
 const error: GTTError = new GTTError('A GDAX API request failed.', err); // TODO add req url here
```

in a method, wait for it, titled `handleResponse` which leads to a lot of head stratching when you see an error message - you can't see from logs _what_ request failed.

Could you kindly fix this.  I could raise a PR but this seems trivial.

Many thanks,

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
