### ISSUE TITLE
gdax's AuthenticatedClient#placeOrder() returns a OrderResult, not an OrderInfo

### ISSUE THREAD

**Issue by blair** [coinbase/coinbase-pro-trading-toolkit#151]
Changing the code in `src/exchanges/gdax/GDAXExchangeAPI.ts` so that tsc can see the types for 
AuthenticatedClient's buy() and sell() methods:

>  \-        const clientMethod = side === 'buy' ? this.authClient.buy.bind(this.authClient) : this.authClient.sell.bind(this.authClient);
>  \-        return clientMethod(gdaxOrder).then((result: OrderInfo) => {
>  \+        const promise = side === 'buy' ? this.authClient.buy(gdaxOrder) : this.authClient.sell(gdaxOrder);
>  \+        return promise.then((result: OrderInfo) => {

> src/exchanges/gdax/GDAXExchangeAPI.ts(253,29): error TS2345: Argument of type '(result: OrderInfo) => LiveOrder | Promise<never>' is not assignable to parameter of type '(value: OrderResult) => PromiseLike<never>'.
>   Types of parameters 'result' and 'value' are incompatible.
>     Type 'OrderResult' is not assignable to type 'OrderInfo'.
>       Property 'funds' is missing in type 'OrderResult'.

which means that the `OrderInfo` should be a `OrderResult` instead. However, changing this also requires that `GDAXOrderToOrder()` cannot be called as is.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
