### ISSUE TITLE
Bitfinex Support - auth channel and trader

### ISSUE THREAD

**Issue by userings** [coinbase/coinbase-pro-trading-toolkit#154]
I understand that GTT is designed to standardise the interaction with various trading platforms. I love it!

I am struggling to understand the nature of the support for Bitfinex. It looks like most of the building blocks are there to place orders and recieve messages related to them however it is not clear how to achieve this.

Unlike GDAX.getSubscribedFeeds, Bitfinex.getSubscribedFeeds does not recieve messages from the 'auth' channel.

If I manually add `feed.subscribe('auth', product);` to this function, messages are recieved in Bitfinex format and printed by the debugger but are not pushed to `feed.on('data',(msg)=>{...`.

I can recieve balance information fine through `GTT.Factories.Bitfinex.DefaultAPI().loadBalances()` but cannot place orders using `GTT.Core.Trader(traderConfig).executeMessage(msg)` using code that works fine with GDAX.

Is the support not really there for Bitfinex or am I doing it wrong?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
