### ISSUE TITLE
Better documenation

### ISSUE THREAD

**Issue by erickeno** [coinbase/coinbase-pro-trading-toolkit#166]
First off, amazing work so far. This is not an issue concerning the code but just a suggestion. At first glance I thought it only entails working with gdax api only but when I dug into the code I realized it does way more. I think with better documentation of the features and how to use them will educate and increase usage and adoption. For example letting people know that ccxt is also included.

**Comment by CjS77** [comment]
Hmm, we put quite a lot of effort into the docs, and while we like to keep the examples GDAX-centric to some degree, there are tutorials that use multiple exchanges. (see https://coinbase.github.io/gdax-tt/gtt_tutorials_tickertape.html)

If there's something lacking doc-wise, could I bounce this back to you to post a PR with some additional explanation / examples that you think would help you navigate the toolkit (and by extension, many others)?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
