### ISSUE TITLE
Ticker Tape Update

### ISSUE THREAD

**Issue by LFoglietti** [coinbase/coinbase-pro-trading-toolkit#175]
I am trying to re-produce the tickertape.  
here is my code:

_"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var GTT = require("gdax-trading-toolkit");
var core_1 = require("gdax-trading-toolkit/build/src/core");
var product = 'BTC-USD';

var logger = GTT.utils.ConsoleLoggerFactory({ level: 'debug' });
    	
GTT.Factories.GDAX.FeedFactory(logger, [product]).then(function (feed) {
    // Configure the live book object
    var config = {
        product: product,
        logger: logger
    };
    var book = new core_1.LiveOrderbook(config);
    book.on('LiveOrderbook.ticker', function (ticker) {
    	var Lastsize = ticker.size;
    	var Lastprice = ticker.price;
    	var Lasttime = ticker.time;
    	console.log(Lastsize + " | " +Lastprice + " | "+ Lasttime);
    });
    book.on('error', function (err) {
        console.log('Livebook errored: ', err);
        feed.pipe(book);
    });
    feed.pipe(book);
   });_ 

It works but when I compare my consolle  to the website Gdax Tickertape I find huge differences, 
for example:
*missing tick;
*different quantities;
* nonsense number when a cascade match occours;

reading on the manual

"The ticker channel provides real-time price updates every time a match happens. It batches updates in case of cascading matches, greatly reducing bandwidth requirements.
Please note that more information will be added to messages from this channel in the near future."

So I guess there is a sort of data manipulation before sending data trough the websocket.
Is my assumption correct or am i doing something wrong with the code?

At the moment my tickertape would be too inaccurate to build any trading strategy.

thanks

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
