### ISSUE TITLE
Has anyone found an incremental technical indicator library?

### ISSUE THREAD

**Issue by sfkiwi** [coinbase/coinbase-pro-trading-toolkit#185]
I'm not sure if this is the best place to ask this but haven't found any other community channels for GTT. 

I'm attempting to implement technical indicators where each indicator implements the abstractMessageTransform interface. This way you can do things like feed.pipe(ema).pipe(sma). I have the SMA working so you can now do something along the lines of:

```
sma_10 = new Sma({ productId: product, period: 10, logger: logger });
sma_20 = new Sma({ productId: product, period: 20, logger: logger });

feed
  .pipe(sma_10)
  .pipe(sma_20)
  .on('data', (msg: any) => {
    if (msg.type === 'ticker' && msg.productId === product) {
      console.log(`Ema (10): ${msg.ema[10]}`);
      console.log(`Ema (20): ${msg.ema[20]}`);
    }
  });
```

First off, has anyone else already implemented something similar?

I was hoping to use the [talib-binding](https://www.npmjs.com/package/talib-binding) node library as the basis for calculating the indicators, however talib is set up to calculate from price[0] -> price[now]. This would mean that for an indicator like an EMA you would need to store an entire history of price data which will eventually run into memory issues. 

Has anyone come across a javascript library that implements TA's as an incremental calculation? What I mean by that is that for an ema period 30, you would give it the last 30 closing price values, but it would memoize its previous ema values so that just the incremental calculation of the next ema can be requested from then on and it would not need to completely recalculate the entire stream. The other solution to this, I believe, is using a reactive programming approach, or to use a directed acyclic graph to map value dependencies (similar to how an excel spreadsheet calculates these types of formulas). Janestreet trading co implemented their [OCaml Incremental Library](https://github.com/janestreet/incremental) to solve this type of problem but these all seem a little extreme for what I'm trying to achieve.

This is relatively trivial to implement for EMA alone but I'd like to do the same for all the indicators included in the original talib library, and ideally avoid having to build an entire DAG library to achieve it. Has anyone already implemented this or know of a more generalizable way to achieve this?

**Comment by atomantic** [comment]
potentially https://github.com/anandanand84/technicalindicators or https://www.npmjs.com/package/tulind would be good places to start. Would love to see something like this baked into this library so it uses the same API style and feeds data in appropriately.

**Comment by sfkiwi** [comment]
I implemented it using `talib-binding` but later found `technicalIndicators` as you mentioned which does have incremental calculation, so after I've ported it across I'll try and add it into the gdax-tt project and do a PR. At the moment its just appending the values onto the TickerMessages (assuming you added it into the stream ahead of your own code.) which works well for moving averages which are calculated each tick but not sure whether that makes sense for all indicators.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
