### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by JPJP73** [coinbase/coinbase-pro-trading-toolkit#193]
Executing
yarn add gdax-trading-toolkit
gives this message:
arning gdax-trading-toolkit > crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
error An unexpected error occurred: "Couldn't find the binary git".

How can I solve this problem?

**Comment by sfkiwi** [comment]
do you have git in your path? I didn't get this error with gdax but I've had it on other projects where I was building on a fresh Amazon instance. It was caused by one of the internal dependencies having a build step that required git and not being able to find it in the path.

**Comment by JPJP73** [comment]
thank you! solved the problem

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
