### ISSUE TITLE
Trader ignores fitOrders in config during constructor

### ISSUE THREAD

**Issue by sfkiwi** [coinbase/coinbase-pro-trading-toolkit#194]
Going by the sample `traderDemo.ts` and the 'TraderConfig' interface it looks like the Trader should set fitOrders as true/false based on the config passed in at instantiation. In the Trader constructor this value is never read. The only way to set `fitOrders` is to call fitOrders on the trader object and set directly.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
