### ISSUE TITLE
Bug: Inconsistent prices provided by the "level2" websocket orderbook channel

### ISSUE THREAD

**Issue by fujiapple852** [coinbase/coinbase-pro-trading-toolkit#195]
Hi,

[Note: This is a issue with the data returned by exchange's websocket feed and not a bug in the client library.  If there is somewhere more appropriate to report this please let me know.]

### The issue
The price *strings* provided by the 'level2' websocket channel are inconsistent between the 'snapshot' and 'l2update' message types.  Specifically I observe that the price *strings* provided in the 'l2update' message have trailing '0' whereas the price *strings* provided in the 'snapshot' messages do not.

### Example
The 'snapshot' message sends the price string "8442.65" whilst the 'l2update' message sends the price string "8442.65000000".

Minimal example code to demonstrate the bug:
https://pastebin.com/gfY0AQ7X

The documentation wisely [states](https://docs.gdax.com/#types) that "Decimal numbers are returned as strings to preserve full precision across platforms" and so I am surprised at the presence of such an inconsistency.

I am also surprised this hasn't been raised before.  By examining some sample code online (i.e. [this](https://github.com/danpaquin/gdax-python/blob/master/gdax/order_book.py) & [this](https://github.com/coinbase/gdax-node/blame/master/lib/orderbook.js)) I believe the explanation may be that the way the order book is typically being maintained is masking the inconsistency.  

In the linked examples the prices are being converted to a exact numeric type and then 'sorted' in some way (i.e. a sorted list or a  red/black tree).  However these approaches are both O(log n) which is undesirable.  It is possible (with some minor unimportant caveats) to maintain an order book and current best bid/ask in O(1) by hashing on the price strings but clearly this relies on the price strings being consistent.

The workaround is to normalise the price strings received from the exchange for both the 'snapshot' and 'l2update' message types however this adds precious time to the critical path and so I would ask this this inconsistency bug be fixed.

Thanks,

Fuji Apple

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
