### ISSUE TITLE
Bug: No ability to set stop limit order

### ISSUE THREAD

**Issue by sfkiwi** [coinbase/coinbase-pro-trading-toolkit#197]
The correct way to set a Stop Limit order on GDAX is to use a Limit order and include parameters for `stop` and `stop_price` (see [GDAX API Reference](https://docs.gdax.com/#place-a-new-order)). In the `placeOrder` method, the `GDAXExchangeAPI` copies across the values from the `PlaceOrderMessage` (defined in gdax-tt) to an `OrderParams` object (defined in gdax-node) but does not include the fields `stop` or `stop_price`. 

This is actually due to the fields not being defined in the gdax-node `index.d.ts` interface and not documented anywhere either. There is an [open issue](https://github.com/coinbase/gdax-node/issues/164) on the gdax-node project about this. 

The gdax library never checks the params before sending so its actually still possible to execute a stop limit order using the gdax library directly, however because the gdax-tt has an intermediary interface its not possible when using the gdax-tt to place the order.

**Comment by sfkiwi** [comment]
I have submitted a PR on the gdax project with the necessary changes to index.d.ts and have implemented the changes required for supporting stop limit orders in the gdax-tt project so once my PR for the gdax changes gets through to a release I can submit a PR to push through the changes for the stop limit orders.

**Comment by DannyHinshaw** [comment]
@sfkiwi this would be really great, thanks for your work on this feature. 

It looks like your [PR was merged](https://github.com/coinbase/gdax-node/pull/286) on the gdax-node project, is you're PR still ready to go for adding this to gdax-tt?

**Comment by sfkiwi** [comment]
@DannyHinshaw I actually did implement this with the intention of doing a PR but only recently realized that my approach may not fully support generalizing it across other exchanges. I'll take another look to see if its ready for a PR.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
