### ISSUE TITLE
Request: Canary version

### ISSUE THREAD

**Issue by sfkiwi** [coinbase/coinbase-pro-trading-toolkit#208]
Would it be possible to have a canary release of the library any time a PR is merged into master? Similar to how chaijs does it? https://github.com/chaijs/chai/issues/751

That way you can use the @canary tag to specify you want the bleeding edge build. For small changes this would speed up development instead of having to wait for the next official release.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
