### ISSUE TITLE
No documented way to access Level3 orderbook

### ISSUE THREAD

**Issue by MaximG1234** [coinbase/coinbase-pro-trading-toolkit#227]
I am trying to use the FULL channel from GDAX and running into some issues. It appears that nowhere among your documentation do you provide an example for how to start and manage a FULL channel orderbook even though the GDAX-TT seems to support this.

After reviewing the source code I have tried to get things working by doing something like this:

```
const gdax = DefaultAPI(null);

const config = {
    channels: ["full"],
    logger: logger,
    wsUrl: GDAXFeed_1.GDAX_WS_FEED
};

const liveBookConfig: LiveBookConfig = {
    product: product,
    logger: logger
};

const feed = ExchangeFeed_1.getFeed(GDAXFeed_1.GDAXFeed, config, product);

const liveOrderBook = new LiveOrderbook(liveBookConfig);

feed.once('websocket-open', () => {
    feed.subscribe([product]).then(() => {
        gdax.loadOrderbook(product).then((book) => {
            var bookState = book.state();
            var snapshotMessage = {
                type: 'snapshot',
                time: new Date(),
                productId: product,
                sequence: bookState.sequence,
                asks: bookState.asks,
                bids: bookState.bids,
                orderPool: book.orderPool
            };
            feed.push(snapshotMessage);
        });
    });
});

feed.on("LiveOrderbook.update", function () {
    debugger;
});

feed.pipe(liveOrderBook);

feed.connect();
```

 but realised that it won't work as expected as the exchangefeed handler is only wired to the socket.

So, how do you push the initial snapshot for the Level3 stream to get the feed initialised correctly?

**Comment by sfkiwi** [comment]
I'm not sure I understand your question so please correct me if I've misunderstood but I think you're asking how to initialize the liveOrderbook with the snapshot message? If that is the case, the liveOrderbook will actually initialize itself. You can listen for the liveorderbook to emit 'LiveOrderbook.snapshot' event if you want to know when its received the snapshot. 

    const config = {
      logger: logger,
      product: product
    };

    const liveBookConfig: LiveBookConfig = {
      product: product,
      logger: logger
    };
 
    const feed = GDAX.getSubscribedFeeds(config, [product]);

    const liveOrderBook = new LiveOrderbook(liveBookConfig);

    liveOrderBook.on('LiveOrderbook.snapshot', (snapshot: SnapshotMessage) => {
       // The live order book has initialized itself with the snapshot
    });

    feed.pipe(liveOrderbook);

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
