### ISSUE TITLE
ccxt: LoadTicker(), ticker's bid value is populated with ask and vice versa

### ISSUE THREAD

**Issue by amynguy86** [coinbase/coinbase-pro-trading-toolkit#252]
https://github.com/coinbase/gdax-tt/blob/cd92a4a8d126d09d557711a92a92c478a502e3f1/src/exchanges/ccxt/index.ts#L275

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
