### ISSUE TITLE
Question: possible to have Trader and LiveOrderbook running simultaneously

### ISSUE THREAD

**Issue by djflux** [coinbase/coinbase-pro-trading-toolkit#254]
This question is similar to the one posed in Issue #136 - Newb question here:

I have my feed piped into a `LiveOrderbook` and it's working with my trading logic, however once the logic thinks it should execute the trade I can't because I have my feed piped into the order book and not the `Trader`.

Is there a method of accomplishing what I want similar to the Limiter in `traderDemos.ts` to either `executeMessage` or `placeTrade` with my `Trader`?

Any pointers are extremely welcome :)

Cheers,
Flux

**Comment by djflux** [comment]
For those curious, I created my own class based on the `Trader` class in the toolkit, instead of having to pipe the gdax-feed into the `Trader` class. My derived class has public methods to handle the messages provided by `LiveOrderbook.`

**Comment by aquaflamingo** [comment]
@djflux would you mind writing a small tutorial or sample to add :)?
