### ISSUE TITLE
Handling for CCXT errors

### ISSUE THREAD

**Issue by Ameobea** [coinbase/coinbase-pro-trading-toolkit#33]
Currently, the CCXT exchange connector has no way of communicating if a method failed or what caused the failure.  For example, in the `loadProducts()` method, if the network request fails, `[]` is returned without any indication to the caller why the request failed.  https://github.com/coinbase/gdax-tt/blob/master/src/exchanges/ccxt/index.ts#L173

In other places, the error is logged to the `Logger` but `null` or `[]` is returned as if the request was successful.

----

I propose either rejecting the promise with an `Error` explaining exactly what went wrong or returning some kind of result data type that can indicate the status of the request.

I'd be happy to work on this implementation myself and put in a PR, but I want to know what approach the maintainers would like to go with before doing anything.

**Comment by kroitor** [comment]
The CCXT itself throws various errors [described here](https://github.com/ccxt-dev/ccxt/wiki/Manual#error-handling), depending on the reason of failure. Most of connectivity errors are handled that way. So, it's just a matter of mapping/wrapping CCXTError(s) to GDAX Trading Toolkit Errors.

**Comment by Ameobea** [comment]
@CjS77 how can I help make this happen?  I see that you've added the beta roadmap tag, but I couldn't find any reference to this particular issue in the roadmap section of the documentation.

If you gave a general description of the way you want this to be implemented, I'd love to jump in and get started on building it out.

**Comment by CjS77** [comment]
It's a note to myself to have it implemented before the Beta release, but I don't have time to look at it right now. If you want to take a stab. you're more than welcome

In general, if a REST call fails, the GTT interface should reject the promise, or resolve with a sane default. So if you handle the ccxt errors, you can direct the error down the appropriate route.

**Comment by kroitor** [comment]
A minor update, the base name of error class was changed from CCXTError to BaseError. This change should not be an issue, as in most cases you deal with derived specific errors for various reasons. Just to keep you updated, guys. Thx for your effort!

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
