### ISSUE TITLE
Bad Request 

### ISSUE THREAD

**Issue by JamesMcMurran** [coinbase/coinbase-pro-trading-toolkit#61]
so I am getting the bellow message but only when my bot is trading massive amounts IDT it is exceeding the 10 request per second. How do I get a better idea of what the error message for? I have also added the code that I use bellow any help would be awesome.

Error: A GDAX API request failed. Bad Request.

            -------Order-------
            type:order
            Time:null
            ProductId:LTC-USD
            OrderType:limit
            Side:buy
            Size:1
            Price:60.14

```javascript
gdaxAPI.placeOrder(order).then((result: LiveOrder) => {
            Message.log(`Order to ${side} ${amount} 'LTC-USD' for${price}. Result: ${result.status} 
            
            -------Order-------
            type:${order.type}
            Time:${order.time}
            ProductId:${order.productId}
            OrderType:${order.orderType}
            Side:${order.side}
            Size:${order.size}
            Price:${order.price}
            
            `);

        }).catch(
            function (message:any) {
            Message.sendMessage(`${message}.
            
            -------Order-------
            type:${order.type}
            Time:${order.time}
            ProductId:${order.productId}
            OrderType:${order.orderType}
            Side:${order.side}
            Size:${order.size}
            Price:${order.price}
            `);
            Message.log(order);
```

**Comment by CjS77** [comment]
Hi James
You might be. I need to improve the error message detail coming back from API requests with the specific reason the order failed.

**Comment by rmm5t** [comment]
I received this same generic error on a limit order. Turned out, I was submitting orders below the `0.01` size threshold, but it wasn't until I tried the exact limit order in the GDAX web interface that I received a reasonable error message back.

**Comment by JamesMcMurran** [comment]
@rmm5t yep I ran into that too =(. So I started having it print the full message it was sending.

@CjS77 That would be awesome. Also if you could point me in the right direction I would be willing to help out with that. 

Also if anyone wants to have a look I just open sourced my basic bot. It is my first open source project and my first typescript and node project as well. It's a simple market maker bot but my idea is to make it so you can link into a stronger processor bot to calc the buy down and profit intervals. It should make it so anyone new can hit the ground running and just focus on the strategy.  Any input is welcome =)

**Comment by CjS77** [comment]
That's awesome! Happy trading, James.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
