### ISSUE TITLE
LiveOrderbook's ticker should update best ask and bid in between ticks

### ISSUE THREAD

**Issue by CjS77** [coinbase/coinbase-pro-trading-toolkit#67]
`LiveOrderbook.ticker` returns the same information as the `ticker` message, which is usually only updated on new trades and not necessarily when the midmarket spread changes.

LiveOrderbook should be smart enough to handle this and keep `bid` and `ask` 100% up to date.

See https://github.com/coinbase/gdax-tt/issues/63

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
