### ISSUE TITLE
Deadlines

### ISSUE THREAD

**Issue by wranai** [coinbase/coinbase-pro-trading-toolkit#8]
I'm not sure about other exchanges, but Poloniex seems to use crude / rude exponential backoff when they can't secure the resources for a request, and many of their responses come as much as two minutes after the request was sent. Waiting that long for a response is unacceptable, so I suggest setting a reasonable deadline for requests (e.g. 3s) after which they could be retried or abandoned (https://visionmedia.github.io/superagent/#timeouts).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
