### ISSUE TITLE
Cancelled order not in my book

### ISSUE THREAD

**Issue by nunoarruda** [coinbase/coinbase-pro-trading-toolkit#80]
I want to execute some code after a trade is completed/fully filled so I have the following event listener in place:
```TS
trader.on('Trader.trade-finalized', (msg: TradeFinalizedMessage) => {
    logger.log('info', 'Order complete', JSON.stringify(msg));
});
```
Now I'm getting the following message instead: `2017-10-28T21:07:28.294Z - warn: Trader: Cancelled order not in my book...`

Why is this happening and how to fix it?

**Comment by BryGuy72** [comment]
I had this similar issue quite often a couple weeks ago when trying. It seems that the book (for one's own orders, not the public orderbook) is buggy. I haven't spent much time debugging. Perhaps a contributor can take a look?

**Comment by CjS77** [comment]
Is the order being placed by the `Trader` object? Or are you placing the trade manually somewhere else?

**Comment by nunoarruda** [comment]
@CjS77 the order is being placed by the Trader object:

```TS
const order: PlaceOrderMessage = {
    time: null,
    type: 'placeOrder',
    productId: 'LTC-EUR',
    size: '1',
    price: '48.50',
    side: 'buy',
    orderType: 'limit',
    postOnly: true
};

trader.executeMessage(order);
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
