### ISSUE TITLE
Avoiding double execution of orders

### ISSUE THREAD

**Issue by wranai** [coinbase/coinbase-pro-trading-toolkit#9]
Placing new orders is tricky because the same order could execute twice if a seemingly timed out order is retried. To solve this (at least on Poloniex, where it's a very real problem), a tiny placeholder order can be placed at a price that won't fill (so there's no risk if it's done twice) and then this placeholder order can be modified ("moveOrder") which is an idempotent operation.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
