### ISSUE TITLE
Placing GDAX market orders into order book seems to be broken.

### ISSUE THREAD

**Issue by adriancooney** [coinbase/coinbase-pro-trading-toolkit#95]
So, I'm use a `Trader` class to place a market order and every attempt at placing a makert order fails. I get this error: 

```
Unable to place order TypeError: Cannot read property 'eq' of null
    at AggregatedLevelWithOrders.addOrder (/Users/adrian/Code/crypto-trader/node_modules/gdax-trading-toolkit/src/lib/BookBuilder.ts:113:24)
    at BookBuilder.add (/Users/adrian/Code/crypto-trader/node_modules/gdax-trading-toolkit/src/lib/BookBuilder.ts:242:20)
    at api.placeOrder.then (/Users/adrian/Code/crypto-trader/node_modules/gdax-trading-toolkit/src/core/Trader.ts:94:31)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

The reason for this error is because the `price` (`this.price` in the stacktrace) passed into the `AggregatedLevelWithOrders` is `null` which is because of [this line](https://github.com/coinbase/gdax-tt/blob/master/src/exchanges/gdax/GDAXExchangeAPI.ts#L508). The reason why *that condition* is true, and the price is being set to `null` is because of this data I'm getting back from the GDAX API once the market order has been placed:

```
{ id: '0c8e7a83-----------------1abc2d0',
     size: '0.01000000',
     product_id: 'ETH-EUR',
     side: 'sell',
     stp: 'dc',
     type: 'market',
     post_only: false,
     created_at: '2017-11-16T01:51:31.372597Z',
     fill_fees: '0.0000000000000000',
     filled_size: '0.00000000',
     executed_value: '0.0000000000000000',
     status: 'pending',
     settled: false }
```

As you can see, the `execute_value` is zero and thus the calculated price is zero. Now, I think this *may* be a bug in GDAX's API but I'm not sure. Should the GDAX API be returning a value greater than zero or is it expected that the `execute_value` be zero? Another reason to suspect a bug in the GDAX API is that interface is showing a fill fee of `0.0071` and in the response above, it's zero.

Edit: The order hasn't been filled, only placed so this data would not exist in the response from the request so I think the GDAX API is good. I'm starting to think this is a bug in the trading toolkit.

Actually, this is related to https://github.com/coinbase/gdax-tt/issues/80. I was getting similar errors but went a couple of steps further debugging.

**Comment by CjS77** [comment]
Related to #93 
Related to #80

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
